### ISSUE TITLE
Missing image files

### ISSUE THREAD

**Issue by s1291** [najibelmokhtari/basic-epidemic-simulation#1]
Hello,
First off, thank you very much for this simulation. It looks very promising. After watching your video, I thought I have to give it a try.
Unfortunately, it looks like the images are missing from the project.

Here is what I get when I try to run the script:

```python
$ python epidemic.py

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "epidemic.py", line 204, in <module>
    main()
  File "epidemic.py", line 101, in main
    init_screen()
  File "epidemic.py", line 69, in init_screen
    image = pygame.image.load("death_toll.png").convert_alpha()
pygame.error: Couldn't open death_toll.png


```

As you can see, the script couldn't find the file `death_toll.png`

Thanks

**Comment by farhatizakaria** [comment]
I got the same problem !

**Comment by s1291** [comment]
As a quick fix, you can use whatever image with a `png` extension and rename it to `death_toll.png`

**Comment by maurusian** [comment]
Any picture with a white background (and named "death_toll.png") should do the trick.

**Comment by najibelmokhtari** [comment]
File has now been added to the repository.
