### ISSUE TITLE
Recreate the simulator Using P5.js.

### ISSUE THREAD

**Issue by adiljouahri** [najibelmokhtari/basic-epidemic-simulation#2]
Hi, i decide to recreate your code to JavaScript with the library P5.js, i think by this way more people can use in any browser.  
if anyone take a look, here the link for the new repository:
https://github.com/adiljouahri/basic-epidemic-simulation-javascript

**Comment by najibelmokhtari** [comment]
Amazing! Thanks for taking this further.
